# <project_root>/.github/workflows/deploy.yml

name: Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

on:
  push:
    branches:
      - master

jobs:
  app-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project dependencies
        uses: ./.github/actions/setup-project
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-codeartifact-repository: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY }}
          aws-codeartifact-domain: ${{ secrets.AWS_CODEARTIFACT_DOMAIN }}
          aws-codeartifact-domain-owner: ${{ secrets.AWS_CODEARTIFACT_DOMAIN_OWNER }}

      - name: Lint code
        run: npm run lint

      - name: Execute unit tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy app to Vercel production env
        uses: ./.github/actions/deploy-vercel
        with:
          vercel-token: ${{ secrets.VERCEL_AUTH_TOKEN }}
          mode: 'production'
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deployed from GitHub Actions'
