# <project_root>/.github/workflows/deploy.yml

name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  app-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project dependencies
        uses: ./.github/actions/setup-project
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-codeartifact-repository: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY }}
          aws-codeartifact-domain: ${{ secrets.AWS_CODEARTIFACT_DOMAIN }}
          aws-codeartifact-domain-owner: ${{ secrets.AWS_CODEARTIFACT_DOMAIN_OWNER }}

      - name: Lint code
        run: npm run lint

      - name: Execute unit tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy app to Vervell preview env
        uses: ./.github/actions/deploy-vercel
        with:
          vercel-token: ${{ secrets.VERCEL_AUTH_TOKEN }}
          mode: 'preview'
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
